createSuccess:
    javascripts:    [grupo.js]

showSuccess:
    javascripts:    [jqplot/jquery.jqplot.min.js, jqplot/jqplot.barRenderer.min.js, jqplot/jqplot.pieRenderer.min.js, jqplot/jqplot.categoryAxisRenderer.min.js, jqplot/jqplot.pointLabels.min.js, jqplot/jqplot.canvasAxisTickRenderer.min.js, jqplot/jqplot.canvasTextRenderer.min.js, graficos/graficosModule.js]
    stylesheets:    [jquery.jqplot.min.css]

newSuccess:
    javascripts:    [grupo.js, InfoJefesNew.js]

editSuccess:
    javascripts:    [grupo.js, InfoJefesEdit.js, bootstrap/bootstrap-tooltip.js, bootstrap/bootstrap-popover.js]

newSuccess:
    javascripts:    [bootstrap/bootstrap-tooltip.js, bootstrap/bootstrap-popover.js]