createSuccess:
    javascripts:    [grupo.js]    

showSuccess:
    javascripts:    [estadisticasGrupo.js, jquery.jqplot.min.js, jqplot/jqplot.barRenderer.min.js, jqplot/jqplot.pieRenderer.min.js, jqplot/jqplot.categoryAxisRenderer.min.js, jqplot/jqplot.pointLabels.min.js, graphFunctions.js]
    stylesheets:    [jquery.jqplot.min.css]

newSuccess:
    javascripts:    [grupo.js, InfoJefesNew.js]

editSuccess:
    javascripts:    [grupo.js, InfoJefesEdit.js, bootstrap-tooltip.js, bootstrap-popover.js]
    
newSuccess:
    javascripts:    [bootstrap-tooltip.js, bootstrap-popover.js]
    
