# You can find more information about this file on the symfony website:
# http

busquedaSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, busqueda_ajax.js, evaluacionJefe.js]

editComentarioSuccess:
    javascripts:    [bootstrap/bootstrap-typeahead.js]

editSuccess:
    javascripts:    [registro.js, jquery.Rut.min.js]

formularioAlojamientoSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, evaluacionJefe.js]
    
formularioCoEvaluacionSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, coEvaluacion.js]

formularioJefeZonaSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, evaluacionJefe.js]

formularioLocalidadSuccess:
    javascripts:    [evaluacionJefe.js, contactosLocalidad.js]

formularioSedeTalleresSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, evaluacionJefe.js]

informacionSuccess:
    javascripts:    [bootstrap/bootstrap-tab.js]
    
informacionUsuarioSuccess:
    javascripts:    [bootstrap/bootstrap-typeahead.js, bootstrap/bootstrap-modal.js]
    
inscritosSuccess:
    javascripts:    [bootstrap/bootstrap-modal.js, postulantes.js, postulantes_ajax.js, usuario_detalle_modal.js, ../sfFormExtraPlugin/js/jquery.autocompleter.js, jquery.Rut.min.js]
    stylesheets:    [../sfFormExtraPlugin/css/jquery.autocompleter.css]

newSuccess:
    javascripts:    [registro.js, jquery.Rut.min.js]
   
recuperarPasswordSuccess:
    javascripts:    [recuperarPassword.js, jquery.Rut.min.js]
    
newComentarioSuccess:
    javascripts:    [bootstrap/bootstrap-typeahead.js]

nuevoProyectoSuccess:
    javascripts:    [bootstrap/bootstrap-typeahead.js]
    
editarUsuarioModalAjaxSuccess:
    has_layout:     false