# You can find more information about this file on the symfony website:
# http

newSuccess:
    javascripts:    [registro.js, jquery.Rut.min.js]
    
editSuccess:
    javascripts:    [registro.js, jquery.Rut.min.js]
    
showSuccess:
    javascripts:    [bootstrap-tab.js ,bootbox.min.js]

editComentarioSuccess:
    javascripts:    [bootstrap-typeahead.js]

recuperarPasswordSuccess:
    javascripts:    [recuperarPassword.js, jquery.Rut.min.js]
    
formularioCoEvaluacionSuccess:
    javascripts:    [bootstrap-modal.js, coEvaluacion.js]
    
informacionSuccess:
    javascripts:    [bootstrap-tab.js]

inscripcionSuccess:
    javascripts:    [bootstrap-tab.js]
    stylesheets:    [inscripcion_web.css]
    
reportesVoluntariosSuccess.php:
    javascripts:    [bootstrap-modal.js, evaluacionJefe.js]