<?php

/**
 * PastoralGrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralGrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralGrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralGrupo');
    }
    
    public function addAllGruposQuery()
    {
        return Doctrine_Query::create()
              ->from('PastoralGrupo g');
    }
    
    public static function getGruposPorIdVersion($id_version){
                
         $q = Doctrine_Query::create()
            ->from('PastoralGrupo g')
            ->where('g.proyecto_version_id = ?',$id_version);
        return $q->execute();  
    }        
    
    public function addGrupoPorProyectoVersionQuery($proyecto_version_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralGrupo g');
        }

        $alias = $q->getRootAlias();
        
        $q  -> where('g.proyecto_version_id = ?',$proyecto_version_id);
        
        return $q;
    }
    
    public function addGrupoPorProyectoQuery($proyect_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralGrupo g');
        }

        $alias = $q->getRootAlias();
        
        $q  -> leftJoin($alias.'.PastoralProyectoVersion pv')
              -> where('pv.proyecto_id = ?',$proyect_id);
        
        return $q;
    }
}