<?php

/**
 * PastoralUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralUsuarioTable extends Doctrine_Table
{    

    public function addExtranjerosQuery(Doctrine_Query $q = null)
    {
      if (is_null($q))
      {
        $q = Doctrine_Query::create()
          ->from('PastoralUsuario u');
      }
      $alias = $q->getRootAlias();
      $q -> andWhere($alias.'.esExtranjero = 1'); 
      return $q;
    }
    
    public function fullLeftJoin(Doctrine_Query $q = null)
    {
          return     $q->leftJoin('u.PastoralMisionUsuarioEstado mue')
          ->leftJOin('mue.PastoralEstadoPostulacion ep')
          ->leftJOin('mue.PastoralMision m')
          ->leftJoin('m.PastoralGrupo g')
          ->leftJoin('m.PastoralLocalidadFantasia lf')
          ->leftJoin('u.User user')
          ->leftJoin('u.PastoralComuna com')
          ->leftJoin('u.PastoralMovimiento mov')
          ->leftJoin('u.PastoralUniversidad uni')
          ->leftJoin('u.PastoralCarrera car')
          ->leftJoin('u.PastoralColegio col')
          ->leftJoin('u.PastoralCurso cur')
          ->leftJoin('u.PastoralUsuarioCargo uc')
          ->leftJoin('g.PastoralProyectoVersion pv')
          ->leftJoin('pv.PastoralProyecto p')
          ->leftJoin('uc.PastoralCargo cargo')
          ;
    }
    
    public function fullSelects(Doctrine_Query $q = null)
    {
        $q->addSelect('mue.id');
        $q->addSelect('mue.flag_zona');
        $q->addSelect('mue.flag_cuota');
        $q->addSelect('mue.cuota');
        $q->addSelect('mue.descripcion_zona');
        $q->addSelect('mue.descripcion_cuota');
        $q->addSelect('m.id');
        $q->addSelect('uc.id');
        $q->addSelect('ep.nombre');
        $q->addSelect('user.email_address');
        $q->addSelect('mov.nombre');
        $q->addSelect('com.nombre');
        $q->addSelect('u.rut');
        $q->addSelect('u.nombre');
        $q->addSelect('u.apellido_paterno');
        $q->addSelect('u.apellido_materno');
        $q->addSelect('u.sexo');
        $q->addSelect('u.enfermedades_alergias');
        $q->addSelect('u.telefono_emergencia');
        $q->addSelect('u.ano_ingreso');
        $q->addSelect('u.fecha_nacimiento');
        $q->addSelect('u.telefono_celular');
        $q->addSelect('u.tipo_institucion_id');
        $q->addSelect('uni.sigla');
        $q->addSelect('uni.nombre');
        $q->addSelect('car.nombre');
        $q->addSelect('cur.nombre');
        $q->addSelect('col.nombre');
        $q->addSelect('lf.nombre');
        $q->addSelect('cargo.nombre');
    return $q;
    }
    public function getQueryConJoins()
    {
        $usuarios = Doctrine_Query::create()->from('PastoralUsuario u');
        $usuarios ->leftJoin('u.PastoralUniversidad uni')
          ->leftJoin('u.PastoralColegio col')
          ->leftJoin('u.PastoralMovimiento mov')
          ->leftJoin('u.PastoralCarrera car')
          ->leftJoin('u.PastoralMisionUsuarioEstado mue')
          ->leftJOin('mue.PastoralMision m')
          ->leftJoin('m.PastoralGrupo g')
          ->leftJoin('g.PastoralProyectoVersion pv')
          ->leftJoin('pv.PastoralProyecto p')
          ->leftJoin('u.PastoralUsuarioCargo uc')
          ->leftJoin('uc.PastoralCargo cargo');
        return $usuarios;
    }
    
    public function addFiltroBusquedaConJoins($busqueda, Doctrine_Query $q = null)
    {
       $busqueda = trim($busqueda);
       $q->andWhere('CONCAT(lower(u.nombre)," ",lower(u.apellido_paterno)," ",lower(u.apellido_materno)) LIKE ? ','%'.trim(strtolower($busqueda)).'%');
       return $q;
    }
    
    public function addAgruparPorUsuarioConJoins(Doctrine_Query $q = null)
    {
           $q->GroupBy('u.id');
           return $q;
    }
    
    public function addFiltroCargoConJoins($cargo,Doctrine_Query $q = null)
    {
           $q->andWhere('cargo.id = ?',$cargo);
           return $q;
    }
    
    public function addFiltroMisionConJoins($mision,Doctrine_Query $q = null)
    {
           $q->andWhere('m.id = ?',$mision);
           return $q;
    }
    
    public function addFiltroGrupoConJoins($grupo,Doctrine_Query $q = null)
    {
           $q->andWhere('g.id = ?',$grupo);
           return $q;
    }
    
    public function addFiltroProyectoVersionConJoins($proyecto_version,Doctrine_Query $q = null)
    {
           $q->andWhere('pv.id = ?',$proyecto_version);
           return $q;
    }
    
    public function addFiltroProyectoConJoins($proyecto,Doctrine_Query $q = null)
    {
           $q->andWhere('p.id = ?',$proyecto);
           return $q;
    }
    
    public function addFiltroSexoMasculinoConJoins(Doctrine_Query $q = null)
    {
           $q->andWhere('u.sexo = "Masculino"');
           return $q;
    }
    
    public function addFiltroSexoFemeninoConJoins(Doctrine_Query $q = null)
    {
           $q->andWhere('u.sexo = "Femenino"');
           return $q;
    }
    
    public function addFiltroUniversidadConJoins($universidad,Doctrine_Query $q = null)
    {
           $q->andWhere('uni.id = ?',$universidad);
           return $q;
    }
    
    public function addFiltroCarreraConJoins($carrera,Doctrine_Query $q = null)
    {
           $q->andWhere('car.id = ?',$carrera);
           return $q;
    }
    
    public function addFiltroMovimientoConJoins($movimiento,Doctrine_Query $q = null)
    {
           $q->andWhere('mov.id = ?',$movimiento);
           return $q;
    }
    
    public function addFiltroRecomendadoPorJefesConJoins(Doctrine_Query $q = null)
    {
           $q->andWhere('mue.recomendado_por_jefes > 0');
           return $q;
    }
    
    public function addFiltroRecomendadoPorMisionerosConJoins(Doctrine_Query $q = null)
    {
           $q->andWhere('mue.recomendado_por_misioneros > 0');
           return $q;
    }
    
     public function getUsuarioPorId($id)
     {
        $q = $this->addUsuarioPorId($id);
        return $q->fetchOne();
     }
     
     public function getUsuarioPorRut($rut)
     {
        $q = Doctrine_Query::create()
          ->from('PastoralUsuario u')
          ->andWhere('u.rut = ?',$rut);
          
         return $q->fetchOne();
     }
	 
	 public function getUsuarioPorNombre($nomb)
     {
      $nombres = explode(" ",$nomb);
          $q = Doctrine_Query::create()
            ->from('PastoralUsuario u')
            ->andWhere('u.nombre = ? AND u.apellido_paterno = ? AND u.apellido_materno = ?',array($nombres[0],$nombres[1],$nombres[2]));
            
           return $q->fetchOne();
     }
     
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralUsuario');
    }


    public function addUsuarioPorId($id, Doctrine_Query $q = null)
    {
      if (is_null($q))
      {
        $q = Doctrine_Query::create()
          ->from('PastoralUsuario u');
      }
      $alias = $q->getRootAlias();
   
      $q ->andWhere($alias .'.id = ?',$id);
   
      return $q;
    }

    public function getArrayUsuariosDeMisionPorUsuario($usuario_id)
    {
       $muc = Doctrine_Core::getTable('PastoralMisionUsuarioCargo')->getMisionPorUsuario($usuario_id);
       if($muc != null)
       {
         return $this->addUsuariosDeMision($id)->fetchArray();
       }
    }
    
    public function addUsuariosDeMision($mision_id, Doctrine_Query $q = null)
    {
       if (is_null($q))
      {
        $q = Doctrine_Query::create()
          ->from('PastoralUsuario u');
      }
      $alias = $q->getRootAlias();
      
      $q  ->leftJoin($alias.'.PastoralMisionUsuarioCargo muc')
          ->leftJoin('muc.PastoralMision m')
          ->where('m.id = ?',$mision_id);
      return $q;
    }

	public function getPotencialesJefes($proyecto_version_id,$jefes_selec, Doctrine_Query $q = null)
    {
			
		$jefes = Doctrine_Core::getTable('PastoralUsuario')->findAll();
		$jefes_retorno = array();
		
			
		foreach($jefes as $jefe)
		{	
			$seguir = 1;
			if($jefes_selec != NULL)
			{
				foreach($jefes_selec as $selec)
				{
					if($selec->getId() == $jefe->getId())
						$seguir = 0;
				}
			}
			if($seguir == 1)
			{
				$jefes_retorno[] = $jefe;
			}
		}
		
		return $jefes_retorno;
    }
    
    public function getArrayUsuarioPorId($usuario_id)
    {
        $q = Doctrine_Query::create()
            ->from('PastoralUsuario u')
            ->where('u.id = ?',$usuario_id);
        return $q->fetchArray();
    }
    
    public function getUsuarioPorInstanciaYPorCargo($proyecto_version_id, $cargo_id){        
        $q1 = Doctrine_Query::create()
            ->from('PastoralUsuarioCargo u')
            ->andWhere('u.proyecto_version_id = ? AND u.cargo_id = ?',array($proyecto_version_id, $cargo_id));
        $usuario_cargo = $q1->execute();
        
        $retorno = array();
        
        foreach($usuario_cargo as $u_cargo){
           $q2 = Doctrine_Query::create()
              ->from('PastoralUsuario u')
              ->where('u.id = ?',$u_cargo->getUsuarioId());         
        
          $retorno = array_merge($retorno, array($q2->fetchOne()));
        }
         return $retorno;   
    }
    
	
	static public function RetornarParaSeleccion($q, $limit)
  { 
    $dql = Doctrine_Query::create()
         ->from('PastoralUsuario p')
    	 ->where('p.nombre LIKE ? OR p.apellido_paterno LIKE ? OR p.apellido_materno LIKE ?', array('%'.$q.'%', '%'.$q.'%', '%'.$q.'%'));
    return $dql->fetchArray();
  }
    
}