<?php

/**
 * PastoralMisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralMisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralMisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralMision');
    }
    
     public function getMisionesInscribiblesPorProyecto( $proyect_id,Doctrine_Query $q = null)
    {
          $q1 = $this->addMisionesPorProyectoQuery($proyect_id,$q);
          $q2 = $this->addMisionesInscribiblesQuery($q1);
          return $q2->execute();
    }
    
    public function addAllMisionesQuery()
    {
        return Doctrine_Query::create()
          ->from('PastoralMision m');
    }
    
    public function leftJoinLocalidadFantasia(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
        }
        $alias = $q->getRootAlias();
        
        return $q->leftJoin($alias.'.PastoralLocalidadFantasia');
    }
    
    public function addMisionesActivasPorProyectoQuery( $proyecto_id,Doctrine_Query $q = null)
    {
          $q1 = $this->addMisionesPorProyectoQuery($proyecto_id,$q);
          $q2 = $this->addMisionesActivasQuery($q1);
          return $q2;
    }
    
    public function addSalidasInscribiblesPorProyectoQuery( $proyecto_id,Doctrine_Query $q = null)
    {
          $q1 = $this->addMisionesPorProyectoQuery($proyect_id,$q);
          $q2 = $this->addMisionesActivasQuery($q1);
          $q3 = $this->addGroupBySalidasQuery($q2);
          return $q3;
    }
    
    public function getSalidasInscribiblesPorProyecto($proyect_id,Doctrine_Query $q = null)
    {
          $q1 = $this->addMisionesPorProyectoQuery($proyect_id,$q);
          $q2 = $this->addMisionesInscribiblesQuery($q1);
          $q3 = $this->addGroupBySalidasQuery($q2);
          return $q3->execute();
           
    }
    
    public function addGroupBySalidasQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
        }
        $alias = $q->getRootAlias();
        
        $q      ->select($alias.'.salida_id')
                ->distinct(true)
                ->groupBy($alias.'.salida_id')
                ->leftJoin($alias.'.PastoralSalida s');
        return $q;
    }    
    
    public function getMisionesInscribiblesPorProyectoYSalidaQuery( $proyecto_id, $salida_id,Doctrine_Query $q = null)
    {
          $q1 = $this->addMisionesPorProyectoQuery($proyecto_id,$q);
          $q2 = $this->addMisionesInscribiblesQuery($q1);
          $q3 = $this->addMissionesPorSalidaQuery($salida_id, $q2);
          
          return $q3;
    }


    
    public function getMisionesPorProyecto($proyect_id, Doctrine_Query $q = null)
    {
        return $this->addMisionesPorProyectoQuery($proyect_id, $q)->execute();
    }
    
    public function getMisionesInscribibles(Doctrine_Query $q = null)
    {
        return $this->addMisionesInscribiblesQuery($q)->execute();
    }
      
    public function getArrayMisionPorId($mision_id)
    {
        $q = Doctrine_Query::create()
            ->from('PastoralMision m')
            ->where('m.id = ?',$mision_id);
        return $q->fetchArray();
    }
	
	  public function addMisionPorIdQuery($mision_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
        }
        
        $alias = $q->getRootAlias();
        
        $q -> andWhere($alias.'.id = ?',$mision_id);
        return $q;
    }
    
    public function addMisionesPorProyectoVersionQuery($proyecto_version_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
        }

        $alias = $q->getRootAlias();
        
        $q  -> leftJoin($alias.'.PastoralGrupo g')
              -> where('g.proyecto_version_id = ?',$proyecto_version_id);
        
        return $q;
    }
    
    public function addMisionesPorProyectoQuery($proyect_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
        }

        $alias = $q->getRootAlias();
        
        $q    -> leftJoin($alias.'.PastoralGrupo g')
              -> leftJoin('g.PastoralProyectoVersion pv')
              -> where('pv.proyecto_id = ?',$proyect_id);
        
        return $q;
    }
    
    public function addMisionesActivasQuery(Doctrine_Query $q = null)
    {
          if (is_null($q))
          {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
          }
          $alias = $q->getRootAlias();
       
          $q ->andWhere($alias.'.fecha_termino > ?',date('Y-m-d H:i:s', time()));
       
          return $q;
    }
      
     public function addMisionesInscribiblesQuery(Doctrine_Query $q = null)
    {
          if (is_null($q))
          {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
          }
          $alias = $q->getRootAlias();
       
          $q ->andWhere($alias . '.inscripcion_abierta = ?',1);
       
          return $q;
    }
    
   public function addMissionesPorSalidaQuery($salida_id, Doctrine_Query $q = null)
   {
        if (is_null($q))
          {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
          }
          
          $alias = $q->getRootAlias();
          
          $q->andWhere($alias.'.salida_id = ?',$salida_id);
          
          return $q;
   } 
   
   public function addMissionesPorGrupoQuery($grupo_id, Doctrine_Query $q = null)
   {
        if (is_null($q))
          {
            $q = Doctrine_Query::create()
              ->from('PastoralMision m');
          }
          
          $alias = $q->getRootAlias();
          
          $q->andWhere($alias.'.grupo_id = ?',$grupo_id);
          
          return $q;
   }
   
   public function getMisionesPorIdGrupo($id_grupo)
    {
        $q = Doctrine_Query::create()
            ->from('PastoralMision m')
            ->where('m.grupo_id = ?',$id_grupo);
        return $q->execute();
    }
      
}