<?php

/**
 * PastoralTipoNecesidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralTipoNecesidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralTipoNecesidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralTipoNecesidad');
    }
    
    public function getTiposNecesidadesQuery()
    {
        $q = Doctrine_Query::create()
            ->from('PastoralTipoNecesidad tn')
            ->where('tn.id > 0');
            
        return $q;
    }
}