<?php

/**
 * PastoralComunaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralComunaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralComunaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralComuna');
    }
    
    static public function getComunasPorBusqueda($q, $limit)
    {       
      $dql = Doctrine_Query::create()
           ->from('PastoralComuna c')
           ->where('lower(c.nombre) LIKE ?', "%$q%");
      return $dql->fetchArray();
    }
}
