<?php

/**
 * PastoralLocalidadFantasiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralLocalidadFantasiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralLocalidadFantasiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralLocalidadFantasia');
    }
    public function getArrayLocalidadFantasiaPorId($localidad_fantasia_id)
    {
        $q = Doctrine_Query::create()
            ->from('PastoralLocalidadFantasia lf')
            ->where('lf.id = ?',$localidad_fantasia_id);
        return $q->fetchArray();
    }
    
    	public function getLocalidadesFantasia()
	  {
		$query = Doctrine_Query::create()
        ->from('PastoralLocalidadFantasia a');
		
		return $query ->execute();		
	  }
    
}