<?php

/**
 * PastoralEstadoPostulacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralEstadoPostulacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralEstadoPostulacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralEstadoPostulacion');
    }
    
        
    public function getArrayEstadoPorId($estado_id)
    {
        $q = Doctrine_Query::create()
            ->from('PastoralEstadoPostulacion ep')
            ->where('ep.id = ?',$estado_id);
        return $q->fetchArray();
    }
}