<?php

/**
 * PastoralCarreraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralCarreraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralCarreraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralCarrera');
    }
}