<?php

/**
 * PastoralPerfilAlojamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralPerfilAlojamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralPerfilAlojamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralPerfilAlojamiento');
    }
}