<?php

/**
 * PastoralColegioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralColegioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralColegioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralColegio');
    }
    
    static public function getColegiosPorBusqueda($q, $limit)
    {
    
    	$dql = Doctrine_Query::create()
    		->from('PastoralColegio c')
    		->where('lower(c.nombre) LIKE ?', "%$q%");
    	return $dql->fetchArray();
    }
}