<?php

/**
 * PastoralUsuarioCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pastoral
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PastoralUsuarioCargo extends BasePastoralUsuarioCargo
{
  public function puedeVerMision($mision)
  {
      
    if($this->getMisionId()== $mision->getId())
    {
      return true;
    }
    if($this->getProyectoVersionId()!= null)
    {
       if($mision->getPastoralGrupo()->getProyectoVersionId() == $this->getProyectoVersionId())
       return true;
       
        if($this->getPastoralCargo()->getNombre() == 'Jefe Nacional'&&$mision->getPastoralGrupo()->getPastoralProyectoVersion()->getProyectoId() == $this->getPastoralProyectoVersion()->getProyectoId())
        return true;
    }
    if($this->getGrupoId()!=null)
    {
      if($this->getGrupoId() == $mision->getGrupoId())
       return true;
    }
		
    return null;
	  
  }
  
  public function puedeEditarMision($mision)
  {
      
    if($this->getMisionId()== $mision->getId())
    {
      return true;
    }
    if($this->getProyectoVersionId()!= null)
    {
       if($mision->getPastoralGrupo()->getProyectoVersionId() == $this->getProyectoVersionId())
       return true;
    }
    if($this->getGrupoId()!=null)
    {
      if($this->getGrupoId() == $mision->getGrupoId())
       return true;
    }
		
    return null;
	  
  }
  
  public function getProyectoVersion()
  {      
    if($this->getProyectoVersionId()!=null)
      return $this->getPastoralProyectoVersion();
    if($this->getGrupoId()!=null)
      return $this->getPastoralGrupo()->getPastoralProyectoVersion();
    if($this->getMisionId()!=null)
      return $this->getPastoralMision()->getPastoralGrupo()->getPastoralProyectoVersion();
		
    return null;	  
  }
  
  public function puedeVerGrupo($grupo)
  {
    if($this->getProyectoVersionId()!= null)
    {
       if($grupo->getProyectoVersionId() == $this->getProyectoVersionId())
       return true;
       
       if($this->getPastoralCargo()->getNombre() == 'Jefe Nacional'&&$grupo->getPastoralProyectoVersion()->getProyectoId() == $this->getPastoralProyectoVersion()->getProyectoId())
        return true;
       
    }
    if($this->getGrupoId()!=null)
    {
      if($this->getGrupoId() == $grupo->getId())
       return true;
    }
		
    return null;	  
  }
  
  public function puedeEditarGrupo($grupo)
  {
    if($this->getProyectoVersionId()!= null)
    {
       if($grupo->getProyectoVersionId() == $this->getProyectoVersionId())
       return true;        
    }
    if($this->getGrupoId()!=null)
    {
      if($this->getGrupoId() == $grupo->getId())
       return true;
    }
		
    return null;
	  
  }
}