<?php

/**
 * PastoralAlojamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralAlojamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralAlojamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralAlojamiento');
    }
}