<?php

/**
 * PastoralLugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralLugarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralLugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralLugar');
    }
    
    public function getLugarYContactosPorId($lugar_id)
    {
      $q = Doctrine_Query::create()
          ->from('PastoralLugar lu')
          ->leftJoin('lu.PastoralTipoContacto tc')
          ->leftJoin('lu.PastoralContacto c')
          ->leftJoin('lu.PastoralPerfilAlojamiento pa')
          ->where('lu.id = ?', $lugar_id);
      return $q->fetchOne();
    }
}