<?php

/**
 * PastoralNecesidadMisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralNecesidadMisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralNecesidadMisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralNecesidadMision');
    }
}