<?php

/**
 * PastoralMovimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralMovimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralMovimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralMovimiento');
    }
}