<?php

/**
 * PastoralMisionFiltroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralMisionFiltroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralMisionFiltroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralMisionFiltro');
    }
}