<?php

/**
 * PastoralCarrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pastoral
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PastoralCarrera extends BasePastoralCarrera
{

  public function __toString()
  {
    return sprintf('%s', $this->getNombre());

  }
  
  public function cantidadPorMision($mision_id)
  {
    $q = Doctrine_Query::create()
            ->select('COUNT(u.carrera_id) as total_id') 
            ->from('PastoralUsuario u')
            ->where('u.carrera_id=?',$this->getId())
            ;
      $alias = $q->getRootAlias();
      $q -> leftJoin($alias.'.PastoralMisionUsuarioEstado mue')
         -> andWhere('mue.mision_id = ?',$mision_id);
         
    $res = $q->fetchArray();         
    return $res[0]['total_id'];
  }
  
  public function cantidadPorGrupo($grupo_id)
  {
    //genero el texto de la query para todas las misiones del grupo
    $datos = array();
    $texto = '';
    $misiones = Doctrine_Core::getTable('PastoralMision')->findByGrupoId($grupo_id);
    if($misiones != null)
    {
    foreach($misiones as $mision)
      {  
        if($texto == '')
          $texto = 'mue.mision_id = ?';
        else
          $texto = $texto.' OR mue.mision_id = ?';
          
        $datos[] = $mision->getId();
      }
    } 
    
    $q = Doctrine_Query::create()
            ->select('COUNT(u.carrera_id) as total_id') 
            ->from('PastoralUsuario u')
            ->where('u.carrera_id=?',$this->getId())
            ;
      $alias = $q->getRootAlias();
      $q -> leftJoin($alias.'.PastoralMisionUsuarioEstado mue')
         -> andWhere($texto,$datos);
         
    $res = $q->fetchArray();         
    return $res[0]['total_id'];
  }
   
  public function cantidad($texto, $datos)
  {    
    $q = Doctrine_Query::create()
            ->select('COUNT(u.carrera_id) as total_id') 
            ->from('PastoralUsuario u')
            ->where('u.carrera_id=?',$this->getId())
            ;
      $alias = $q->getRootAlias();
      $q -> leftJoin($alias.'.PastoralMisionUsuarioEstado mue')
         -> andWhere($texto,$datos);
         
    $res = $q->fetchArray();         
    return $res[0]['total_id'];
  }
  

}