<?php

/**
 * PastoralFiltroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralFiltroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralFiltroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralFiltro');
    }
	public function addFiltros(Doctrine_Query $q = null)
    {
       if (is_null($q))
      {
        $q = Doctrine_Query::create()
          ->from('PastoralFiltro f');
      }
      return $q;
    }
}