<?php

/**
 * PastoralCursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralCursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralCursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralCurso');
    }
}