<?php

/**
 * PastoralPerfilAlojamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pastoral
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PastoralPerfilAlojamiento extends BasePastoralPerfilAlojamiento
{
    public function reset()
    {
       $columns = Doctrine_Core::getTable('PastoralPerfilAlojamiento')->getColumnNames();
       foreach($columns as $column)
       {
          if($column != "id" && $column != "lugar_id")
          {
            $this->set($column, 0);
          }
       }

    }
}