<?php

/**
 * PastoralPerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralPerfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralPerfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralPerfil');
    }
}