<?php

/**
 * PastoralProyectoVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralProyectoVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralProyectoVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralProyectoVersion');
    }	
	  
    public function getActivos()
	  {
        $query = Doctrine_Query::create()
        ->from('PastoralProyectoVersion a')
        ->where('a.ano >= ?', date("Y"));
		
		return $query ->execute();
		
	  }

    public function getYaExisteVersion($ano, $version, $id_proyecto){
      $query = Doctrine_Query::create()
          ->from('PastoralProyectoVersion a')
          ->where('a.ano = ?', $ano)
          ->andWhere('a.version = ?', $version)
          ->andWhere('a.proyecto_id = ?', $id_proyecto);
      
      return $query->execute();

    }  
    public function addAllProyectoVersionQuery()
    {
              return Doctrine_Query::create()
              ->from('PastoralProyectoVersion a');
    }
    public function leftJoinProyecto(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralProyectoVersion a');
        }
        $alias = $q->getRootAlias();
        
        return $q->leftJoin($alias.'.PastoralProyecto p');
    }
    
    public function addProyectoVersionPorProyecto($proyecto_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralProyectoVersion a');
        }

        $alias = $q->getRootAlias();
        
        $q  -> where($alias.'.proyecto_id = ?',$proyecto_id);
        
        return $q;
    }
    
    public function addUltimoProyectoVersionDeProyecto($proyecto_id,Doctrine_Query $q = null)
    {
    // SELECT * FROM `Table` ORDER BY `id` DESC LIMIT 1;
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralProyectoVersion a');
        }

        $alias = $q->getRootAlias();
        
        $q  -> where('a.proyecto_id = ?',$proyecto_id)
            -> orderBy('a.id DESC')
            -> limit(1)
            ;
        
        return $q;
    }
   
}