<?php

/**
 * PastoralTipoContactoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralTipoContactoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralTipoContactoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralTipoContacto');
    }
}