<?php

/**
 * PastoralSalidaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralSalidaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralSalidaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralSalida');
    }
	
	public function getSalidas()
	  {
		$query = Doctrine_Query::create()
        ->from('PastoralSalida a');
		
		return $query ->execute();		
	  }
    
    
    public function getSalidaPorId($id_salida)
	  {
		$query = Doctrine_Query::create()
        ->from('PastoralSalida a')
        ->where('a.id = ?',$id_salida);
		
		return $query ->fetchOne();		
	  }

}