<?php

/**
 * PastoralTipoInstitucionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralTipoInstitucionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralTipoInstitucionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralTipoInstitucion');
    }
}