<?php

/**
 * PastoralContactoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralContactoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralContactoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralContacto');
    }
    
    public function addContactosPorLocalidadQuery($localidad_id, Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralContacto c');
        }

        $alias = $q->getRootAlias();
        
        $q  ->where($alias.'.localidad_id = ?',$localidad_id)
            ->orderBy($alias.'.tipo_contacto_id');
        return $q;
    }
    
 
}