<?php

/**
 * PastoralProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralProyecto');
    }
    
    public static function getNombreProyectoPorId($proyecto_id){
                
         $q = Doctrine_Query::create()
            ->from('PastoralProyecto p')
            ->where('p.id = ?',$proyecto_id);
        return $q->fetchOne();  
    }
    
    public function getProyectos()
	  {
		$query = Doctrine_Query::create()
        ->from('PastoralProyecto a');
		
		return $query ->execute();		
	  } 
    
}