<?php

/**
 * PastoralExtranjeroInscritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralExtranjeroInscritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralExtranjeroInscritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralExtranjeroInscrito');
    }
    
    public function fullLeftJoin(Doctrine_Query $q = null)
    {
          return     $q->leftJoin('ei.PastoralUsuario u')
          ->leftJoin('u.PastoralMisionUsuarioEstado mue')
          ->leftJOin('mue.PastoralEstadoPostulacion ep')
          ->leftJOin('mue.PastoralMision m')
          ->leftJoin('m.PastoralGrupo g')
          ->leftJoin('m.PastoralLocalidadFantasia lf')
          ->leftJoin('u.User user')
          ->leftJoin('u.PastoralComuna com')
          ->leftJoin('u.PastoralMovimiento mov')
          ->leftJoin('u.PastoralUniversidad uni')
          ->leftJoin('u.PastoralCarrera car')
          ->leftJoin('u.PastoralColegio col')
          ->leftJoin('u.PastoralCurso cur')
          ->leftJoin('u.PastoralUsuarioCargo uc')
          ->leftJoin('g.PastoralProyectoVersion pv')
          ->leftJoin('pv.PastoralProyecto p')
          ->leftJoin('uc.PastoralCargo cargo')
          ;
    }
    
    
    public function fullSelects(Doctrine_Query $q = null)
    {
        $q->addSelect('ei.proyecto_version_id ');
        $q->addSelect('mue.id');
        $q->addSelect('mue.flag_zona');
        $q->addSelect('mue.flag_cuota');
        $q->addSelect('mue.cuota');
        $q->addSelect('mue.descripcion_zona');
        $q->addSelect('mue.descripcion_cuota');
        $q->addSelect('m.id');
        $q->addSelect('uc.id');
        $q->addSelect('ep.nombre');
        $q->addSelect('user.email_address');
        $q->addSelect('mov.nombre');
        $q->addSelect('com.nombre');
        $q->addSelect('u.rut');
        $q->addSelect('u.nombre');
        $q->addSelect('u.apellido_paterno');
        $q->addSelect('u.apellido_materno');
        $q->addSelect('u.sexo');
        $q->addSelect('u.enfermedades_alergias');
        $q->addSelect('u.telefono_emergencia');
        $q->addSelect('u.ano_ingreso');
        $q->addSelect('u.fecha_nacimiento');
        $q->addSelect('u.telefono_celular');
        $q->addSelect('u.tipo_institucion_id');
        $q->addSelect('uni.sigla');
        $q->addSelect('uni.nombre');
        $q->addSelect('car.nombre');
        $q->addSelect('cur.nombre');
        $q->addSelect('col.nombre');
        $q->addSelect('lf.nombre');
        $q->addSelect('cargo.nombre');
    return $q;
    }
    
}