<?php

/**
 * PastoralNotificacionUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralNotificacionUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralNotificacionUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralNotificacionUsuario');
    }
    
    public function countNotificacionesNuevasDeUsuario($usuario_id)
    {
      $q = $this->addNotificacionesPorUsuarioQuery($usuario_id);
      
      $alias = $q->getRootAlias();
      
      $q -> andWhere($alias.'.leido = 0');
         
      return $q->count();
    }
    
    public function getTopNotificacionesPorUsuarioQuery($usuario_id)
    {
      $limite = 5; 
      $q1 = $this->addNotificacionesPorUsuarioQuery($usuario_id);
      $q2 = $this->addNotificacionesLimiteQuery($limite,$q1);
      return $q2;
    }
    
    public function addNotificacionesLimiteQuery($limite, Doctrine_Query $q = null)
    {
         if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralNotificacionUsuario nu');
        }

        $alias = $q->getRootAlias();
        
        $q -> addOrderBy($alias.'.leido ASC')
           -> addOrderBy($alias.'.created_at ASC')
           -> limit($limite);
        return $q;
    }
    
    public function addNotificacionesPorUsuarioQuery($usuario_id, Doctrine_Query $q = null)
    {
         if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralNotificacionUsuario nu');
        }

        $alias = $q->getRootAlias();
        
        $q -> andWhere($alias.'.recibe_id = ?',$usuario_id);
        return $q;
    }
    
    
}