<?php

/**
 * PastoralUniversidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pastoral
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PastoralUniversidad extends BasePastoralUniversidad
{

  public function __toString()
  {
    return sprintf('%s', $this->getNombre());

  }
  
  public function cantidadPorMision($mision_id)
  {
    $q = Doctrine_Query::create()
            ->select('COUNT(u.universidad_id) as total_id') 
            ->from('PastoralUsuario u')
            ->where('u.universidad_id=?',$this->getId())
            ;
      $alias = $q->getRootAlias();
      $q -> leftJoin($alias.'.PastoralMisionUsuarioEstado mue')
         -> andWhere('mue.mision_id = ?',$mision_id);
         
    $res = $q->fetchArray();         
    return $res[0]['total_id'];
  }

}