<?php

/**
 * PastoralMisionUsuarioEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralMisionUsuarioEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralMisionUsuarioEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralMisionUsuarioEstado');
    }
    
    public function fullLeftJoin(Doctrine_Query $q = null)
    {
          return     $q->leftJoin('mue.PastoralUsuario u')
          ->leftJOin('mue.PastoralEstadoPostulacion ep')
          ->leftJOin('mue.PastoralMision m')
          ->leftJoin('m.PastoralGrupo g')
          ->leftJoin('m.PastoralLocalidadFantasia lf')
          ->leftJoin('u.User user')
          ->leftJoin('u.PastoralComuna com')
          ->leftJoin('u.PastoralMovimiento mov')
          ->leftJoin('u.PastoralUniversidad uni')
          ->leftJoin('u.PastoralCarrera car')
          ->leftJoin('u.PastoralColegio col')
          ->leftJoin('u.PastoralCurso cur')
          ->leftJoin('u.PastoralUsuarioCargo uc')
          ->leftJoin('g.PastoralProyectoVersion pv')
          ->leftJoin('pv.PastoralProyecto p')
          ->leftJoin('uc.PastoralCargo cargo')
          ;
    }
    
    public function fullSelects(Doctrine_Query $q = null)
    {
        $q->addSelect('mue.id');
        $q->addSelect('mue.flag_zona');
        $q->addSelect('mue.flag_cuota');
        $q->addSelect('mue.cuota');
        $q->addSelect('mue.descripcion_zona');
        $q->addSelect('mue.descripcion_cuota');
        $q->addSelect('m.id');
        $q->addSelect('uc.id');
        $q->addSelect('ep.nombre');
        $q->addSelect('user.email_address');
        $q->addSelect('mov.nombre');
        $q->addSelect('com.nombre');
        $q->addSelect('u.rut');
        $q->addSelect('u.nombre');
        $q->addSelect('u.apellido_paterno');
        $q->addSelect('u.apellido_materno');
        $q->addSelect('u.sexo');
        $q->addSelect('u.enfermedades_alergias');
        $q->addSelect('u.telefono_emergencia');
        $q->addSelect('u.ano_ingreso');
        $q->addSelect('u.fecha_nacimiento');
        $q->addSelect('u.telefono_celular');
        $q->addSelect('u.tipo_institucion_id');
        $q->addSelect('uni.sigla');
        $q->addSelect('uni.nombre');
        $q->addSelect('car.nombre');
        $q->addSelect('cur.nombre');
        $q->addSelect('col.nombre');
        $q->addSelect('lf.nombre');
        $q->addSelect('cargo.nombre');
    return $q;
    }
    public function getInfoMisionConJoinsPorUsuarioQuerry($usuario_id)
    {
        $q = Doctrine_Query::create()
          ->from('PastoralMisionUsuarioEstado mue')
          ->leftJOin('mue.PastoralEstadoPostulacion ep')
          ->leftJOin('mue.PastoralMision m')
          ->leftJoin('m.PastoralGrupo g')
          ->leftJoin('g.PastoralProyectoVersion pv')
          ->leftJoin('pv.PastoralProyecto p')
          ->leftJoin('m.PastoralLocalidadFantasia lf')
          ->andWhere('mue.usuario_id = ?',$usuario_id);
          return $q;
    }
    
     //------------------------------------------------------EX MUC------------------------------------------------------------
    public function addMUEporMisionActivaYUsuarioQuery($usuario_id, Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }

        $alias = $q->getRootAlias();
        
        $q  ->leftJoin($alias.'.PastoralMision m')
            ->where($alias.'.usuario_id = ?',$usuario_id)
            ->andWhere('m.fecha_inicio < ?',date('Y-m-d H:i:s', time()))
            ->andWhere('m.fecha_termino > ?',date('Y-m-d H:i:s', time()));
        return $q;
    }

    //------------------------------------------------------------------------------------------------------------------------
    //------------------------------------------------------EX UEM------------------------------------------------------------
    public function addAgruparPorMisionesQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q ->   select($alias.'.mision_id DISTINCT m.localidad_fantasia_id')
                ->leftJoin($alias.'.PastoralMision m')
                ->addGroupBy('m.localidad_fantasia_id')
                ;
        return $q;
    }
    
    public function addAgruparPorEstadosQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q ->   select($alias.'.estado_postulacion_id')
                ->distinct(true)
                ->groupBy($alias.'.estado_postulacion_id')
                ;
        return $q;
    }
    
    public function addMUEporMisionQuery($mision_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> andwhere($alias.'.mision_id = ?',$mision_id);
        return $q;
    }
    
    public function addMUEporGrupoQuery($grupo_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q  -> leftJoin($alias.'.PastoralMision m')
            -> andwhere('m.grupo_id = ?',$grupo_id);
        return $q;
    }
    
    public function addMUEporProyetoVersionQuery($proyecto_version_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q  -> leftJoin($alias.'.PastoralMision m')
            -> leftJoin('m.PastoralGrupo g')
            -> andwhere('g.proyecto_version_id = ?',$proyecto_version_id);
        return $q;
    }
    
    public function addMUEporProyectoQuery($proyecto_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q  -> leftJoin($alias.'.PastoralMision m')
            -> leftJoin('m.PastoralGrupo g')
            -> leftJoin('g.PastoralProyectoVersion pv')
            -> andwhere('pv.proyecto_id = ?',$proyecto_id);
        return $q;
    }
    
    public function addMUEporMovimientoQuery($movimiento_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> leftJoin($alias.'.PastoralUsuario u ')
           -> leftJoin('u.PastoralMovimiento mov')
           -> andWhere('mov.id = ?',$movimiento_id);
    }
    
    public function addMUEporUniversidadQuery($universidad_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> leftJoin($alias.'.PastoralUsuario u ')
           -> leftJoin('u.PastoralUniversidad uni')
           -> andWhere('uni.id = ?',$universidad_id);
    }
    
    public function addMUEporMujeresQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> leftJoin($alias.'.PastoralUsuario u ')
           -> andWhere('u.sexo = "Femenino"')
        ;
        return $q;
    }
    
    public function addMUEporHombresQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> leftJoin($alias.'.PastoralUsuario u ')
           -> andWhere('u.sexo = "Masculino"')
        ;
        return $q;
    }
    
    public function addMUEporProyectoVersionActivoQuery($proyecto_version_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> leftJoin($alias.'.PastoralMision m')
           -> andwhere('m.proyecto_version_id = ?',$proyecto_version_id)
            ->andWhere('m.fecha_inicio < ?',date('Y-m-d H:i:s', time()))
            ->andWhere('m.fecha_termino > ?',date('Y-m-d H:i:s', time()));
           
        return $q;
    }
    
    public function addMUEporUsuarioQuery($usuario_id, Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> andwhere($alias.'.usuario_id = ?',$usuario_id);
        return $q;
    }
    
    public function addMUEporCargoQuery($cargo_id, Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> andwhere($alias.'.cargo_id = ?',$cargo_id);
        return $q;
    }
    
    public function addMUEporEstadoPostulacionQuery($estado_postulacion_id,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q -> andwhere($alias.'.estado_postulacion_id = ?',$estado_postulacion_id);
        return $q;
    }
    
    public function addMUEporEstadoPostulacionActivosQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }
        $alias = $q->getRootAlias();
        $q ->andWhereIn($alias.'.estado_postulacion_id',array(3,4,7));
        return $q;
    }
    
    public function addMUEporFlagZonaQuery($flag,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }

        $alias = $q->getRootAlias();
        
        $q -> andwhere($alias.'.flag_zona = ?',$flag);
        
        return $q;
    }
    
    public function addMUEporFlagCuotaQuery($flag,Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
              ->from('PastoralMisionUsuarioEstado mue');
        }

        $alias = $q->getRootAlias();
        
        $q -> andwhere($alias.'.flag_cuota = ?',$flag);
        
        return $q;
    }
    //------------------------------------------------------------------------------------------------------------------------
    
    public function getMUESporIdUsuario($id){
    
      $q = Doctrine_Query::create()
          ->from('PastoralMisionUsuarioEstado mue')
          ->where('mue.usuario_id = ?', $id);
          
      return $q->execute();    
    
    }

    
}