<?php

/**
 * PastoralEstadoNecesidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastoralEstadoNecesidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastoralEstadoNecesidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PastoralEstadoNecesidad');
    }
}