<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    public function getGuardUserByUsername($name)
    {
        $q = Doctrine_Query::create()
          ->from('sfGuardUser sf')
          ->andWhere('sf.username = ?',$name);
          
         return $q->fetchOne();
    }
}