# You can find more information about this file on the symfony website:
# http


newSuccess:
    javascripts:    [proyectoJefesChoosen.js,  InfoJefesProyectoNew.js]

editJefeSuccess:    
    javascripts:    [proyectoVersionEditarJefe.js]
    

indexSuccess:
    javascripts:    [proyecto.js, jqplot/jquery.jqplot.min.js, jqplot/jqplot.barRenderer.min.js, jqplot/jqplot.pieRenderer.min.js, jqplot/jqplot.categoryAxisRenderer.min.js, jqplot/jqplot.pointLabels.min.js, graficos/graphFunctions.js]
    stylesheets:    [jquery.jqplot.min.css]
    
menuInstanciaSuccess:
    javascripts:    [proyecto.js, jqplot/jquery.jqplot.min.js, jqplot/jqplot.barRenderer.min.js, jqplot/jqplot.pieRenderer.min.js, jqplot/jqplot.categoryAxisRenderer.min.js, jqplot/jqplot.pointLabels.min.js, graficos/graphFunctions.js, graficos/GraficoInscritosAcumulado.js]
    stylesheets:    [jquery.jqplot.min.css]

estadisticasVersionSuccess:
    javascripts:    [proyecto.js, jqplot/jquery.jqplot.min.js, jqplot/jqplot.barRenderer.min.js, jqplot/jqplot.pieRenderer.min.js, jqplot/jqplot.categoryAxisRenderer.min.js, jqplot/jqplot.pointLabels.min.js, graficos/graphFunctions.js, graficos/graphProyecto.js]
    stylesheets:    [jquery.jqplot.min.css]
    
grupoSuccess:
    javascripts:    [proyecto.js]
    
masJefesInstanciaSuccess:    
    javascripts:    [proyectoVersionMasJefes.js]
